In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
file_path = "StudentsPerformance.csv"
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "spscientist/students-performance-in-exams",
  file_path,)

/tmp/ipykernel_3889/2767373062.py:4: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'students-performance-in-exams' dataset.

In [ ]:
print("tamaño", df.shape)

tamaño (1000, 8)

In [ ]:
print("Nombre de columnas", df.head(0))

Nombre de columnas Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

In [ ]:
print("Tipos de datos", df.info(1))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
Tipos de datos None

In [ ]:
print(df.describe)

<bound method NDFrame.describe of      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>

In [ ]:
nulos = df.isnull().sum()
print(nulos[nulos >0])

Series([], dtype: int64)

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
Q1 = df['math score'].quantile(0.25)
Q3 = df['math score'].quantile(0.75)
iqr = Q3 - Q1
inf = Q1 - 1.5 * iqr
sup = Q3 + 1.5 * iqr
df_filtrado = df[df['math score'].between(inf, sup)]
total_atipicos = df[(df['math score'] < inf) | (df['math score'] > sup)].shape[0]
print(total_atipicos)

8

In [ ]:
print(df[~df['math score'].between(inf, sup)])

     gender race/ethnicity parental level of education         lunch  \
17   female        group B            some high school  free/reduced
59   female        group C            some high school  free/reduced
145  female        group C                some college  free/reduced
338  female        group B            some high school  free/reduced
466  female        group D          associate's degree  free/reduced
787  female        group B                some college      standard
842  female        group B                 high school  free/reduced
980  female        group B                 high school  free/reduced

    test preparation course  math score  reading score  writing score
17                     none          18             32             28
59                     none           0             17             10
145                    none          22             39             33
338                    none          24             38             27
466                    none          26             31             38
787                    none          19             38             32
842               completed          23             44             36
980                    none           8             24             23

In [ ]:
df["gender"].value_counts()
df["gender"].value_counts(normalize=True) * 100

gender
female    51.8
male      48.2
Name: proportion, dtype: float64

In [ ]:
df["math score"].describe()

count    1000.00000
mean       66.08900
std        15.16308
min         0.00000
25%        57.00000
50%        66.00000
75%        77.00000
max       100.00000
Name: math score, dtype: float64